export {default as GitHubsvg} from './GitHubsvg';
export {default as LinkedInsvg} from './LinkedInsvg';
export {default as StackOFsvg} from './StackOFsvg';
export {default as Homesvg} from './Homesvg';
export {default as Gmailsvg} from './Gmailsvg';
export {default as Arrowsvg} from './Arrowsvg';
export {default as Slacksvg} from './Slacksvg';
export {default as Imagesvg} from './Imagesvg';
export {default as UnderConstruction} from './UnderConstruction';
